
package com.iceportal.services.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-10T19:42:10.891+01:00
 * Generated source version: 3.1.10
 * 
 */
public final class ICEWebServiceHttpGet_ICEWebServiceHttpGet_Client {

    private static final QName SERVICE_NAME = new QName("http://services.iceportal.com/service", "ICEWebService");

    private ICEWebServiceHttpGet_ICEWebServiceHttpGet_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ICEWebService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ICEWebService ss = new ICEWebService(wsdlURL, SERVICE_NAME);
        ICEWebServiceHttpGet port = ss.getICEWebServiceHttpGet();  
        
        {
        System.out.println("Invoking searchBrochuresV2...");
        java.lang.String _searchBrochuresV2_did = "";
        java.lang.String _searchBrochuresV2_hotelName = "";
        java.lang.String _searchBrochuresV2_city = "";
        java.lang.String _searchBrochuresV2_state = "";
        java.lang.String _searchBrochuresV2_country = "";
        java.lang.String _searchBrochuresV2_region = "";
        java.lang.String _searchBrochuresV2_type = "";
        java.lang.String _searchBrochuresV2_videosExist = "";
        java.lang.String _searchBrochuresV2_hd360SExist = "";
        java.lang.String _searchBrochuresV2_photosExist = "";
        java.lang.String _searchBrochuresV2_iFrameExist = "";
        java.lang.String _searchBrochuresV2_customContentExist = "";
        java.lang.String _searchBrochuresV2_pageSize = "";
        java.lang.String _searchBrochuresV2_pageNumber = "";
        com.iceportal.services.service.SearchBrchureInfoV2 _searchBrochuresV2__return = port.searchBrochuresV2(_searchBrochuresV2_did, _searchBrochuresV2_hotelName, _searchBrochuresV2_city, _searchBrochuresV2_state, _searchBrochuresV2_country, _searchBrochuresV2_region, _searchBrochuresV2_type, _searchBrochuresV2_videosExist, _searchBrochuresV2_hd360SExist, _searchBrochuresV2_photosExist, _searchBrochuresV2_iFrameExist, _searchBrochuresV2_customContentExist, _searchBrochuresV2_pageSize, _searchBrochuresV2_pageNumber);
        System.out.println("searchBrochuresV2.result=" + _searchBrochuresV2__return);


        }
        {
        System.out.println("Invoking searchBrochures...");
        java.lang.String _searchBrochures_did = "";
        java.lang.String _searchBrochures_hotelName = "";
        java.lang.String _searchBrochures_city = "";
        java.lang.String _searchBrochures_state = "";
        java.lang.String _searchBrochures_country = "";
        java.lang.String _searchBrochures_region = "";
        java.lang.String _searchBrochures_type = "";
        java.lang.String _searchBrochures_videosExist = "";
        java.lang.String _searchBrochures_vRsExist = "";
        java.lang.String _searchBrochures_photosExist = "";
        java.lang.String _searchBrochures_infoExist = "";
        java.lang.String _searchBrochures_generalInfoExist = "";
        java.lang.String _searchBrochures_locationInfoExist = "";
        java.lang.String _searchBrochures_pdfExist = "";
        java.lang.String _searchBrochures_rrExist = "";
        java.lang.String _searchBrochures_pageSize = "";
        java.lang.String _searchBrochures_pageNumber = "";
        com.iceportal.services.service.SearchBrochureInfo _searchBrochures__return = port.searchBrochures(_searchBrochures_did, _searchBrochures_hotelName, _searchBrochures_city, _searchBrochures_state, _searchBrochures_country, _searchBrochures_region, _searchBrochures_type, _searchBrochures_videosExist, _searchBrochures_vRsExist, _searchBrochures_photosExist, _searchBrochures_infoExist, _searchBrochures_generalInfoExist, _searchBrochures_locationInfoExist, _searchBrochures_pdfExist, _searchBrochures_rrExist, _searchBrochures_pageSize, _searchBrochures_pageNumber);
        System.out.println("searchBrochures.result=" + _searchBrochures__return);


        }

        System.exit(0);
    }

}
