package com.iceportal.services.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-09-18T14:33:56.857+01:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://services.iceportal.com/service", name = "ICEWebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ICEWebServiceSoap {

    /**
     * Obtains Room Type Parameters associated with a property
     */
    @WebMethod(operationName = "GetRoomTypesForPropertyV2", action = "http://services.iceportal.com/service/GetRoomTypesForPropertyV2")
    @RequestWrapper(localName = "GetRoomTypesForPropertyV2", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetRoomTypesForPropertyV2")
    @ResponseWrapper(localName = "GetRoomTypesForPropertyV2Response", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetRoomTypesForPropertyV2Response")
    public void getRoomTypesForPropertyV2(
        @WebParam(name = "MappedID", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String mappedID,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetRoomTypesForPropertyV2Result", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.Integer> getRoomTypesForPropertyV2Result,
        @WebParam(mode = WebParam.Mode.OUT, name = "ErrorMessage", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.String> errorMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "roomTypes", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<RoomTypesWithDetails> roomTypes
    );

    /**
     * Obtains brochure content for GetVisuals web service
     */
    @WebMethod(operationName = "GetVisuals", action = "http://services.iceportal.com/service/GetVisuals")
    @RequestWrapper(localName = "GetVisuals", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetVisuals")
    @ResponseWrapper(localName = "GetVisualsResponse", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetVisualsResponse")
    public void getVisuals(
        @WebParam(name = "MappedID", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String mappedID,
        @WebParam(name = "protocol", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String protocol,
        @WebParam(name = "LinkType", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String linkType,
        @WebParam(name = "PhotoSize", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String photoSize,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetVisualsResult", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.Integer> getVisualsResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "ErrorMessage", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.String> errorMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "Property", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<PropertyVisuals> property
    );

    /**
     * Obtains Room Type Parameters associated with an image
     */
    @WebMethod(operationName = "GetRoomTypesForImage", action = "http://services.iceportal.com/service/GetRoomTypesForImage")
    @RequestWrapper(localName = "GetRoomTypesForImage", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetRoomTypesForImage")
    @ResponseWrapper(localName = "GetRoomTypesForImageResponse", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetRoomTypesForImageResponse")
    public void getRoomTypesForImage(
        @WebParam(name = "publicID", targetNamespace = "http://services.iceportal.com/service")
        int publicID,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetRoomTypesForImageResult", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.Integer> getRoomTypesForImageResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "ErrorMessage", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.String> errorMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "roomTypeCodes", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<RoomTypeCodes> roomTypeCodes
    );

    /**
     * Searches for the brochures which match given criteria
     */
    @WebMethod(operationName = "SearchBrochuresV2", action = "http://services.iceportal.com/service/SearchBrochuresV2")
    @RequestWrapper(localName = "SearchBrochuresV2", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.SearchBrochuresV2")
    @ResponseWrapper(localName = "SearchBrochuresV2Response", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.SearchBrochuresV2Response")
    @WebResult(name = "SearchBrochuresV2Result", targetNamespace = "http://services.iceportal.com/service")
    public com.iceportal.services.service.SearchBrchureInfoV2 searchBrochuresV2(
        @WebParam(name = "DID", targetNamespace = "http://services.iceportal.com/service")
        int did,
        @WebParam(name = "hotelName", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String hotelName,
        @WebParam(name = "city", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String city,
        @WebParam(name = "state", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String state,
        @WebParam(name = "country", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String country,
        @WebParam(name = "region", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String region,
        @WebParam(name = "type", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String type,
        @WebParam(name = "videosExist", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String videosExist,
        @WebParam(name = "HD360sExist", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String hd360SExist,
        @WebParam(name = "photosExist", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String photosExist,
        @WebParam(name = "iFrameExist", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String iFrameExist,
        @WebParam(name = "customContentExist", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String customContentExist,
        @WebParam(name = "pageSize", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String pageSize,
        @WebParam(name = "pageNumber", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String pageNumber
    );

    /**
     * Searches for the brochures which match given criteria
     */
    @WebMethod(operationName = "SearchBrochures", action = "http://services.iceportal.com/service/SearchBrochures")
    @RequestWrapper(localName = "SearchBrochures", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.SearchBrochures")
    @ResponseWrapper(localName = "SearchBrochuresResponse", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.SearchBrochuresResponse")
    @WebResult(name = "SearchBrochuresResult", targetNamespace = "http://services.iceportal.com/service")
    public com.iceportal.services.service.SearchBrochureInfo searchBrochures(
        @WebParam(name = "DID", targetNamespace = "http://services.iceportal.com/service")
        int did,
        @WebParam(name = "hotelName", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String hotelName,
        @WebParam(name = "city", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String city,
        @WebParam(name = "state", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String state,
        @WebParam(name = "country", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String country,
        @WebParam(name = "region", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String region,
        @WebParam(name = "type", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String type,
        @WebParam(name = "videosExist", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String videosExist,
        @WebParam(name = "VRsExist", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String vRsExist,
        @WebParam(name = "photosExist", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String photosExist,
        @WebParam(name = "infoExist", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String infoExist,
        @WebParam(name = "generalInfoExist", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String generalInfoExist,
        @WebParam(name = "locationInfoExist", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String locationInfoExist,
        @WebParam(name = "pdfExist", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String pdfExist,
        @WebParam(name = "rrExist", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String rrExist,
        @WebParam(name = "pageSize", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String pageSize,
        @WebParam(name = "pageNumber", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String pageNumber
    );

    /**
     * Obtains brochure IDs that has been changed after specified date
     */
    @WebMethod(operationName = "GetNewBrochuresSince", action = "http://services.iceportal.com/service/GetNewBrochuresSince")
    @RequestWrapper(localName = "GetNewBrochuresSince", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetNewBrochuresSince")
    @ResponseWrapper(localName = "GetNewBrochuresSinceResponse", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetNewBrochuresSinceResponse")
    public void getNewBrochuresSince(
        @WebParam(name = "datefrom", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.datatype.XMLGregorianCalendar datefrom,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetNewBrochuresSinceResult", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.Integer> getNewBrochuresSinceResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "ErrorMessage", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.String> errorMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "info", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<ArrayOfBrochureInfo> info
    );

    /**
     * Obtains brochure IDs that has been changed after specified date
     */
    @WebMethod(operationName = "GetNewBrochureIDsSince", action = "http://services.iceportal.com/service/GetNewBrochureIDsSince")
    @RequestWrapper(localName = "GetNewBrochureIDsSince", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetNewBrochureIDsSince")
    @ResponseWrapper(localName = "GetNewBrochureIDsSinceResponse", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetNewBrochureIDsSinceResponse")
    public void getNewBrochureIDsSince(
        @WebParam(name = "datefrom", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.datatype.XMLGregorianCalendar datefrom,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetNewBrochureIDsSinceResult", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.Integer> getNewBrochureIDsSinceResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "ErrorMessage", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.String> errorMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "info", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<ArrayOfBrochureInfos> info
    );

    /**
     * Obtains Room Type Parameters associated with a property
     */
    @WebMethod(operationName = "GetRoomTypesForProperty", action = "http://services.iceportal.com/service/GetRoomTypesForProperty")
    @RequestWrapper(localName = "GetRoomTypesForProperty", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetRoomTypesForProperty")
    @ResponseWrapper(localName = "GetRoomTypesForPropertyResponse", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetRoomTypesForPropertyResponse")
    public void getRoomTypesForProperty(
        @WebParam(name = "MappedID", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String mappedID,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetRoomTypesForPropertyResult", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.Integer> getRoomTypesForPropertyResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "ErrorMessage", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.String> errorMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "roomTypes", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<ArrayOfRoomType> roomTypes
    );

    /**
     * Obtains brochure IDs for the distrbutor
     */
    @WebMethod(operationName = "GetAllBrochureIDs", action = "http://services.iceportal.com/service/GetAllBrochureIDs")
    @RequestWrapper(localName = "GetAllBrochureIDs", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetAllBrochureIDs")
    @ResponseWrapper(localName = "GetAllBrochureIDsResponse", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetAllBrochureIDsResponse")
    public void getAllBrochureIDs(
        @WebParam(mode = WebParam.Mode.OUT, name = "GetAllBrochureIDsResult", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.Integer> getAllBrochureIDsResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "ErrorMessage", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.String> errorMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "IDs", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<ArrayOfString> iDs
    );

    /**
     * Obtains publicId's of images for specified property with specified roomTypeCode 
     */
    @WebMethod(operationName = "GetImagesOfRoomTypeV2", action = "http://services.iceportal.com/service/GetImagesOfRoomTypeV2")
    @RequestWrapper(localName = "GetImagesOfRoomTypeV2", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetImagesOfRoomTypeV2")
    @ResponseWrapper(localName = "GetImagesOfRoomTypeV2Response", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetImagesOfRoomTypeV2Response")
    public void getImagesOfRoomTypeV2(
        @WebParam(name = "roomTypeCode", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String roomTypeCode,
        @WebParam(name = "MappedID", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String mappedID,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetImagesOfRoomTypeV2Result", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.Integer> getImagesOfRoomTypeV2Result,
        @WebParam(mode = WebParam.Mode.OUT, name = "ErrorMessage", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.String> errorMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "Images", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<ArrayOfImage> images
    );

    /**
     * Obtains brochures for GetProperties Web Service Method
     */
    @WebMethod(operationName = "GetProperties", action = "http://services.iceportal.com/service/GetProperties")
    @RequestWrapper(localName = "GetProperties", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetProperties")
    @ResponseWrapper(localName = "GetPropertiesResponse", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetPropertiesResponse")
    public void getProperties(
        @WebParam(name = "publicationStatus", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String publicationStatus,
        @WebParam(name = "modifiedTypeOption", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String modifiedTypeOption,
        @WebParam(name = "sinceDate", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String sinceDate,
        @WebParam(name = "propertyType", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String propertyType,
        @WebParam(name = "includeSupplierInfo", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String includeSupplierInfo,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetPropertiesResult", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.Integer> getPropertiesResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "ErrorMessage", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.String> errorMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "info", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<ArrayOfPropertyIDInfo> info
    );

    /**
     * Obtains brochure information for GetPropertyInfoV1 web service
     */
    @WebMethod(operationName = "GetPropertyInfoV1", action = "http://services.iceportal.com/service/GetPropertyInfoV1")
    @RequestWrapper(localName = "GetPropertyInfoV1", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetPropertyInfoV1")
    @ResponseWrapper(localName = "GetPropertyInfoV1Response", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetPropertyInfoV1Response")
    public void getPropertyInfoV1(
        @WebParam(name = "MappedID", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String mappedID,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetPropertyInfoV1Result", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.Integer> getPropertyInfoV1Result,
        @WebParam(mode = WebParam.Mode.OUT, name = "ErrorMessage", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.String> errorMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "brochure", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<PropertyInfoV1> brochure
    );

    /**
     * Obtains ICEID from SearchAccountID and MappedID for UserAccountID
     */
    @WebMethod(operationName = "LookupMappedID", action = "http://services.iceportal.com/service/LookupMappedID")
    @RequestWrapper(localName = "LookupMappedID", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.LookupMappedID")
    @ResponseWrapper(localName = "LookupMappedIDResponse", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.LookupMappedIDResponse")
    public void lookupMappedID(
        @WebParam(name = "SearchAccountID", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String searchAccountID,
        @WebParam(name = "SearchMType", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String searchMType,
        @WebParam(name = "SearchMappedID", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String searchMappedID,
        @WebParam(mode = WebParam.Mode.OUT, name = "LookupMappedIDResult", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.Integer> lookupMappedIDResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "ErrorMessage", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.String> errorMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "MappingInfo", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<LookupMappedIDInfo> mappingInfo
    );

    /**
     * Obtains language list
     */
    @WebMethod(operationName = "GetLanguages", action = "http://services.iceportal.com/service/GetLanguages")
    @RequestWrapper(localName = "GetLanguages", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetLanguages")
    @ResponseWrapper(localName = "GetLanguagesResponse", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetLanguagesResponse")
    public void getLanguages(
        @WebParam(mode = WebParam.Mode.OUT, name = "GetLanguagesResult", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.Integer> getLanguagesResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "ErrorMessage", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.String> errorMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "languages", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<ArrayOfItem> languages
    );

    /**
     * Obtains brochure content with direct video links
     */
    @WebMethod(operationName = "GetDirectVideoLinks", action = "http://services.iceportal.com/service/GetDirectVideoLinks")
    @RequestWrapper(localName = "GetDirectVideoLinks", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetDirectVideoLinks")
    @ResponseWrapper(localName = "GetDirectVideoLinksResponse", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetDirectVideoLinksResponse")
    public void getDirectVideoLinks(
        @WebParam(name = "MappedID", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String mappedID,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetDirectVideoLinksResult", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.Integer> getDirectVideoLinksResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "ErrorMessage", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.String> errorMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "brochure", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<Brochure> brochure
    );

    /**
     * Obtains brochure IDs that has been changed during specified period
     */
    @WebMethod(operationName = "GetNewBrochures", action = "http://services.iceportal.com/service/GetNewBrochures")
    @RequestWrapper(localName = "GetNewBrochures", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetNewBrochures")
    @ResponseWrapper(localName = "GetNewBrochuresResponse", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetNewBrochuresResponse")
    public void getNewBrochures(
        @WebParam(name = "datefrom", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.datatype.XMLGregorianCalendar datefrom,
        @WebParam(name = "dateto", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.datatype.XMLGregorianCalendar dateto,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetNewBrochuresResult", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.Integer> getNewBrochuresResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "ErrorMessage", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.String> errorMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "info", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<ArrayOfBrochureInfo> info
    );

    /**
     * Obtains brochure status (enabled/disabled)
     */
    @WebMethod(operationName = "GetBrochureStatus", action = "http://services.iceportal.com/service/GetBrochureStatus")
    @RequestWrapper(localName = "GetBrochureStatus", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetBrochureStatus")
    @ResponseWrapper(localName = "GetBrochureStatusResponse", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetBrochureStatusResponse")
    public void getBrochureStatus(
        @WebParam(name = "MappedID", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String mappedID,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetBrochureStatusResult", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.Integer> getBrochureStatusResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "ErrorMessage", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.String> errorMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "Enabled", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.Boolean> enabled,
        @WebParam(mode = WebParam.Mode.OUT, name = "Published", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.Boolean> published
    );

    /**
     * Obtains region list
     */
    @WebMethod(operationName = "GetRegions", action = "http://services.iceportal.com/service/GetRegions")
    @RequestWrapper(localName = "GetRegions", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetRegions")
    @ResponseWrapper(localName = "GetRegionsResponse", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetRegionsResponse")
    public void getRegions(
        @WebParam(mode = WebParam.Mode.OUT, name = "GetRegionsResult", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.Integer> getRegionsResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "ErrorMessage", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.String> errorMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "region", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.util.List<com.iceportal.services.service.BrochureListItem>> region
    );

    /**
     * Obtains brochure content
     */
    @WebMethod(operationName = "GetBrochure", action = "http://services.iceportal.com/service/GetBrochure")
    @RequestWrapper(localName = "GetBrochure", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetBrochure")
    @ResponseWrapper(localName = "GetBrochureResponse", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetBrochureResponse")
    public void getBrochure(
        @WebParam(name = "MappedID", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String mappedID,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetBrochureResult", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.Integer> getBrochureResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "ErrorMessage", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.String> errorMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "brochure", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<Brochure> brochure
    );

    /**
     * Obtains brochure mapping parameters
     */
    @WebMethod(operationName = "GetMappingInfo", action = "http://services.iceportal.com/service/GetMappingInfo")
    @RequestWrapper(localName = "GetMappingInfo", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetMappingInfo")
    @ResponseWrapper(localName = "GetMappingInfoResponse", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetMappingInfoResponse")
    public void getMappingInfo(
        @WebParam(name = "MappedID", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String mappedID,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetMappingInfoResult", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.Integer> getMappingInfoResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "ErrorMessage", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.String> errorMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "info", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<MappingInfo> info
    );

    /**
     * Obtains region list
     */
    @WebMethod(operationName = "GetStates", action = "http://services.iceportal.com/service/GetStates")
    @RequestWrapper(localName = "GetStates", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetStates")
    @ResponseWrapper(localName = "GetStatesResponse", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetStatesResponse")
    public void getStates(
        @WebParam(name = "CountryID", targetNamespace = "http://services.iceportal.com/service")
        int countryID,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetStatesResult", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.Integer> getStatesResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "ErrorMessage", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.String> errorMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "state", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.util.List<com.iceportal.services.service.BrochureListItem>> state
    );

    /**
     * Obtains publicId's of images for specified property with specified roomTypeCode 
     */
    @WebMethod(operationName = "GetImagesOfRoomType", action = "http://services.iceportal.com/service/GetImagesOfRoomType")
    @RequestWrapper(localName = "GetImagesOfRoomType", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetImagesOfRoomType")
    @ResponseWrapper(localName = "GetImagesOfRoomTypeResponse", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetImagesOfRoomTypeResponse")
    public void getImagesOfRoomType(
        @WebParam(name = "roomTypeCode", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String roomTypeCode,
        @WebParam(name = "MappedID", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String mappedID,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetImagesOfRoomTypeResult", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.Integer> getImagesOfRoomTypeResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "ErrorMessage", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.String> errorMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "Images", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<ArrayOfImage> images
    );

    /**
     * Obtains PreIceTag for 
     */
    @WebMethod(operationName = "GetPrecICETags", action = "http://services.iceportal.com/service/GetPrecICETags")
    @RequestWrapper(localName = "GetPrecICETags", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetPrecICETags")
    @ResponseWrapper(localName = "GetPrecICETagsResponse", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetPrecICETagsResponse")
    public void getPrecICETags(
        @WebParam(mode = WebParam.Mode.OUT, name = "GetPrecICETagsResult", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.Integer> getPrecICETagsResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "ErrorMessage", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.String> errorMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "PreIceTags", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<PrecIceTagsList> preIceTags
    );

    /**
     * Obtains brochure IDs that has been changed after specified date
     */
    @WebMethod(operationName = "GetUpdatedBrochureIDsSinceV1", action = "http://services.iceportal.com/service/GetUpdatedBrochureIDsSinceV1")
    @RequestWrapper(localName = "GetUpdatedBrochureIDsSinceV1", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetUpdatedBrochureIDsSinceV1")
    @ResponseWrapper(localName = "GetUpdatedBrochureIDsSinceV1Response", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetUpdatedBrochureIDsSinceV1Response")
    public void getUpdatedBrochureIDsSinceV1(
        @WebParam(name = "datefrom", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.datatype.XMLGregorianCalendar datefrom,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetUpdatedBrochureIDsSinceV1Result", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.Integer> getUpdatedBrochureIDsSinceV1Result,
        @WebParam(mode = WebParam.Mode.OUT, name = "ErrorMessage", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.String> errorMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "info", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<ArrayOfUpdatedBrochureIDInfoV1> info
    );

    /**
     * Obtains brochures mapping parameters for the distributor
     */
    @WebMethod(operationName = "GetAllMappings", action = "http://services.iceportal.com/service/GetAllMappings")
    @RequestWrapper(localName = "GetAllMappings", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetAllMappings")
    @ResponseWrapper(localName = "GetAllMappingsResponse", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetAllMappingsResponse")
    public void getAllMappings(
        @WebParam(mode = WebParam.Mode.OUT, name = "GetAllMappingsResult", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.Integer> getAllMappingsResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "ErrorMessage", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.String> errorMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "info", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<ArrayOfMappingInfo> info
    );

    /**
     * Obtains brochure IDs and PropertyInfoLastUpdated and ContentLastUpdated for the distrbutor
     */
    @WebMethod(operationName = "GetAllBrochureIDsV2", action = "http://services.iceportal.com/service/GetAllBrochureIDsV2")
    @RequestWrapper(localName = "GetAllBrochureIDsV2", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetAllBrochureIDsV2")
    @ResponseWrapper(localName = "GetAllBrochureIDsV2Response", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetAllBrochureIDsV2Response")
    public void getAllBrochureIDsV2(
        @WebParam(mode = WebParam.Mode.OUT, name = "GetAllBrochureIDsV2Result", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.Integer> getAllBrochureIDsV2Result,
        @WebParam(mode = WebParam.Mode.OUT, name = "ErrorMessage", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.String> errorMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "IDinfo", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<ArrayOfBrochureIDInfo> iDinfo
    );

    /**
     * Obtains brochure IDs and other information that has been changed after specified date
     */
    @WebMethod(operationName = "GetUpdatedBrochuresSince", action = "http://services.iceportal.com/service/GetUpdatedBrochuresSince")
    @RequestWrapper(localName = "GetUpdatedBrochuresSince", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetUpdatedBrochuresSince")
    @ResponseWrapper(localName = "GetUpdatedBrochuresSinceResponse", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetUpdatedBrochuresSinceResponse")
    public void getUpdatedBrochuresSince(
        @WebParam(name = "datefrom", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.datatype.XMLGregorianCalendar datefrom,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetUpdatedBrochuresSinceResult", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.Integer> getUpdatedBrochuresSinceResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "ErrorMessage", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.String> errorMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "info", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<ArrayOfUpdatedBrochureInfo> info
    );

    /**
     * Obtains country list
     */
    @WebMethod(operationName = "GetCountries", action = "http://services.iceportal.com/service/GetCountries")
    @RequestWrapper(localName = "GetCountries", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetCountries")
    @ResponseWrapper(localName = "GetCountriesResponse", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetCountriesResponse")
    public void getCountries(
        @WebParam(mode = WebParam.Mode.OUT, name = "GetCountriesResult", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.Integer> getCountriesResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "ErrorMessage", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.String> errorMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "country", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.util.List<com.iceportal.services.service.BrochureListItem>> country
    );

    /**
     * Obtains package list
     */
    @WebMethod(operationName = "GetPropertyTypes", action = "http://services.iceportal.com/service/GetPropertyTypes")
    @RequestWrapper(localName = "GetPropertyTypes", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetPropertyTypes")
    @ResponseWrapper(localName = "GetPropertyTypesResponse", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetPropertyTypesResponse")
    public void getPropertyTypes(
        @WebParam(mode = WebParam.Mode.OUT, name = "GetPropertyTypesResult", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.Integer> getPropertyTypesResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "ErrorMessage", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.String> errorMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "type", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.util.List<com.iceportal.services.service.BrochureListItem>> type
    );

    /**
     * Obtains brochure content for GetVisualsV2 web service
     */
    @WebMethod(operationName = "GetVisualsV2", action = "http://services.iceportal.com/service/GetVisualsV2")
    @RequestWrapper(localName = "GetVisualsV2", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetVisualsV2")
    @ResponseWrapper(localName = "GetVisualsV2Response", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetVisualsV2Response")
    public void getVisualsV2(
        @WebParam(name = "MappedID", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String mappedID,
        @WebParam(name = "protocol", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String protocol,
        @WebParam(name = "LinkType", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String linkType,
        @WebParam(name = "PhotoSize", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String photoSize,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetVisualsV2Result", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.Integer> getVisualsV2Result,
        @WebParam(mode = WebParam.Mode.OUT, name = "ErrorMessage", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.String> errorMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "Property", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<PropertyVisualsV2> property
    );

    /**
     * Obtains Room Type Parameters associated with an image
     */
    @WebMethod(operationName = "GetRoomTypesForImageV2", action = "http://services.iceportal.com/service/GetRoomTypesForImageV2")
    @RequestWrapper(localName = "GetRoomTypesForImageV2", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetRoomTypesForImageV2")
    @ResponseWrapper(localName = "GetRoomTypesForImageV2Response", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetRoomTypesForImageV2Response")
    public void getRoomTypesForImageV2(
        @WebParam(name = "publicID", targetNamespace = "http://services.iceportal.com/service")
        int publicID,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetRoomTypesForImageV2Result", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.Integer> getRoomTypesForImageV2Result,
        @WebParam(mode = WebParam.Mode.OUT, name = "ErrorMessage", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.String> errorMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "roomTypes", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<RoomTypesWithDetailsV2> roomTypes
    );

    /**
     * Obtains brochure IDs that has been changed after specified date
     */
    @WebMethod(operationName = "GetUpdatedBrochureIDsSince", action = "http://services.iceportal.com/service/GetUpdatedBrochureIDsSince")
    @RequestWrapper(localName = "GetUpdatedBrochureIDsSince", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetUpdatedBrochureIDsSince")
    @ResponseWrapper(localName = "GetUpdatedBrochureIDsSinceResponse", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetUpdatedBrochureIDsSinceResponse")
    public void getUpdatedBrochureIDsSince(
        @WebParam(name = "datefrom", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.datatype.XMLGregorianCalendar datefrom,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetUpdatedBrochureIDsSinceResult", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.Integer> getUpdatedBrochureIDsSinceResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "ErrorMessage", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.String> errorMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "info", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<ArrayOfUpdatedBrochureIDInfo> info
    );

    /**
     * Obtains brochure content for GetBrochureV2 web service
     */
    @WebMethod(operationName = "GetBrochureV2", action = "http://services.iceportal.com/service/GetBrochureV2")
    @RequestWrapper(localName = "GetBrochureV2", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetBrochureV2")
    @ResponseWrapper(localName = "GetBrochureV2Response", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetBrochureV2Response")
    public void getBrochureV2(
        @WebParam(name = "MappedID", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String mappedID,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetBrochureV2Result", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.Integer> getBrochureV2Result,
        @WebParam(mode = WebParam.Mode.OUT, name = "ErrorMessage", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.String> errorMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "brochure", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<BrochureV2> brochure
    );

    /**
     * Obtains ICE category ID, ICE Category name and OTA Category ID, OTA Category Name
     */
    @WebMethod(operationName = "GetCategories", action = "http://services.iceportal.com/service/GetCategories")
    @RequestWrapper(localName = "GetCategories", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetCategories")
    @ResponseWrapper(localName = "GetCategoriesResponse", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetCategoriesResponse")
    public void getCategories(
        @WebParam(mode = WebParam.Mode.OUT, name = "GetCategoriesResult", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.Integer> getCategoriesResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "ErrorMessage", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.String> errorMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "OTACategories", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<ArrayOfCategories> otaCategories,
        @WebParam(mode = WebParam.Mode.OUT, name = "ICECategories", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<ArrayOfICESubCategories> iceCategories
    );

    /**
     * Obtains brochure content for GetBrochureV1 web service
     */
    @WebMethod(operationName = "GetBrochureV1", action = "http://services.iceportal.com/service/GetBrochureV1")
    @RequestWrapper(localName = "GetBrochureV1", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetBrochureV1")
    @ResponseWrapper(localName = "GetBrochureV1Response", targetNamespace = "http://services.iceportal.com/service", className = "com.iceportal.services.service.GetBrochureV1Response")
    public void getBrochureV1(
        @WebParam(name = "MappedID", targetNamespace = "http://services.iceportal.com/service")
        java.lang.String mappedID,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetBrochureV1Result", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.Integer> getBrochureV1Result,
        @WebParam(mode = WebParam.Mode.OUT, name = "ErrorMessage", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<java.lang.String> errorMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "brochure", targetNamespace = "http://services.iceportal.com/service")
        javax.xml.ws.Holder<BrochureV1> brochure
    );
}
